require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'spec/rails_helper.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - Guardfile
    - Gemfile
    - app/models/ability.rb
  DisplayCopNames: true

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/BlockDelimiters:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleblockdelimiters

Style/Documentation:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styledocumentation

Style/DotPosition:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styledotposition

Style/MultilineBlockChain:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylemultilineblockchain

# Github's code views fit 101 character without horizontal scrolling
Metrics/LineLength:
  Max: 101

# Half-screen
Metrics/MethodLength:
  Max: 28

Metrics/AbcSize:
  Max: 30

Rails:
  Enabled: true

RSpec/DescribedClass:
  Enabled: false
